### ISSUE TITLE
Backporting into multiple branches fails

### ISSUE THREAD

**Issue by mtupitsyn** [syndesisio/backport-action#48]
When more then one backport label is assigned to PR, post-merge action fails. Processing for 1st label succeeds, but for 2nd label it fails, claiming:

    Performing backport
    ...
    remote: 
    remote: Create a pull request for 'backport/21-to-release/1.0' on GitHub by visiting:        
    remote:      https://github.com/mtupitsyn/test-actions/pull/new/backport/21-to-release/1.0        
    remote: 
    ...
    Performing backport
    ...
    Error: Unable to clone from repository `https://github.com/mtupitsyn/test-actions.git` a branch named `release/1.1`, this should not have happened ()
    ...

Enabling debug output reveals, that script fails on attempt to do a git clone, while repository was already cloned into target folder at previous iteration:

    ::group::Performing backport
    Performing backport
      ##[debug]Backporting pull request #21 to branch release/1.1
      ##[debug]running: git clone -q --no-tags -b release/1.1 https://github.com/mtupitsyn/test-actions.git /home/runner/work/test-actions/test-actions
      ##[debug]err:fatal: destination path '/home/runner/work/test-actions/test-actions' already exists and is not an empty directory.
      ##[debug]rc=128
      Error: Unable to clone from repository `https://github.com/mtupitsyn/test-actions.git` a branch named `release/1.1`, this should not have happened ()
      ::endgroup:

Attached full log output: [logs_49.zip](https://github.com/syndesisio/backport-action/files/7287205/logs_49.zip)

**Comment by mtupitsyn** [comment]
Proposed https://github.com/syndesisio/backport-action/pull/49 which should have fixed that.

**Comment by zregvart** [comment]
Thanks for the PR!
